"""
docs_writer.py
--------------
Writes (and incrementally updates) one Markdown file per alphabet letter
inside the OUTPUT_DIR folder.

File layout:  portfolio_docs/A.md, B.md … Z.md
Each developer gets a compact section:

    ### 1. Aaaabad Ahmed · Software Engineer
    🔗 [sawad.framer.website](https://sawad.framer.website) · 7 projects

    **NajmAI** · [link](https://…)
    - What it is / does.
    - How it was built or a notable feature.
"""

from pathlib import Path
from urllib.parse import urlparse

from config import OUTPUT_DIR


# ── Internal helpers ──────────────────────────────────────────────────────────

def _ensure_output_dir() -> Path:
    path = Path(OUTPUT_DIR)
    path.mkdir(parents=True, exist_ok=True)
    return path


def _doc_path(letter: str) -> Path:
    return _ensure_output_dir() / f"{letter.upper()}.md"


def _one_line(text: str) -> str:
    return " ".join((text or "").split())


def render_entry(index: int, name: str, role: str, url: str,
                 projects: list[dict]) -> str:
    """Render one developer's section as Markdown."""
    title = f"### {index}. {_one_line(name)}"
    if role:
        title += f" · {_one_line(role)}"

    display = urlparse(url).netloc or url
    count = len(projects)
    meta = f"🔗 [{display}]({url})"
    if projects and not projects[0]["name"].startswith("Portfolio overview"):
        meta += f" · {count} project{'s' if count != 1 else ''}"

    lines = [title, meta, ""]
    if not projects:
        lines.append("_No projects could be extracted — the site may be down "
                     "or block automated visits._")
        lines.append("")
    for p in projects:
        head = f"**{_one_line(p['name'])}**"
        if p.get("url"):
            head += f" · [link]({p['url']})"
        lines.append(head)
        for b in p["bullets"][:2]:
            lines.append(f"- {_one_line(b)}")
        lines.append("")
    return "\n".join(lines) + "\n"


# ── Public API ────────────────────────────────────────────────────────────────

def init_doc(letter: str) -> None:
    """Create (or overwrite) the doc file for *letter* with a header."""
    path = _doc_path(letter)
    header = (
        f"# Developer Portfolios — {letter.upper()}\n\n"
        f"> Auto-generated by Portfolio Analyzer Agent · "
        f"2 points per project\n\n"
        f"---\n\n"
    )
    path.write_text(header, encoding="utf-8")


def append_entry(letter: str, markdown: str) -> None:
    """Append one rendered developer section to the letter's doc file."""
    path = _doc_path(letter)

    # Create the file with header if it doesn't exist yet
    if not path.exists():
        init_doc(letter)

    with open(path, "a", encoding="utf-8") as f:
        f.write(markdown)


def write_index(all_entries: list[dict]) -> None:
    """
    Write a top-level INDEX.md that lists every letter with its entry count
    and a hyperlink to the individual letter docs.
    """
    path = _ensure_output_dir() / "INDEX.md"

    # Count entries per letter
    from collections import Counter
    counts: Counter = Counter(e["letter"] for e in all_entries)

    lines = [
        "# Developer Portfolio Analysis — Index\n",
        "> Auto-generated by Portfolio Analyzer Agent\n",
        f"> Total portfolios analysed: **{len(all_entries)}**\n\n",
        "| Letter | Count | File |\n",
        "|--------|-------|------|\n",
    ]
    for letter in sorted(counts):
        count = counts[letter]
        lines.append(f"| {letter} | {count} | [{letter}.md](./{letter}.md) |\n")

    path.write_text("".join(lines), encoding="utf-8")
    print(f"[docs_writer] Index written → {path}")


def write_summary_stats(stats: dict) -> None:
    """Append a statistics block to INDEX.md after processing completes."""
    path = _ensure_output_dir() / "INDEX.md"

    block = (
        "\n---\n\n"
        "## Run Statistics\n\n"
        f"- **Total processed:** {stats.get('total', 0)}\n"
        f"- **Successful scrapes:** {stats.get('scraped_ok', 0)}\n"
        f"- **Failed / empty:** {stats.get('failed', 0)}\n"
        f"- **Projects summarised:** {stats.get('projects', 0)}\n"
        f"- **AI summaries generated:** {stats.get('ai_ok', 0)}\n"
        f"- **Heuristic fallbacks:** {stats.get('heuristic', 0)}\n"
    )

    with open(path, "a", encoding="utf-8") as f:
        f.write(block)
